---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: thousandeyes-agent
  namespace: thousandeyes
  labels:
    app: thousandeyes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: thousandeyes-browserbot
  namespace: thousandeyes
  labels:
    app: thousandeyes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: thousandeyes-log
  namespace: thousandeyes
  labels:
    app: thousandeyes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
